heat_template_version: 2013-05-23

description: >
  Created 9/25/17 by ucdpadmin. For Cloud admin@Azure-1

parameters:
  flavor:
    type: string
    description: 'Flavor to be used for compute instance'
  admin_user:
    type: string
    description: 'The administrator user for the server'
  admin_pass:
    type: string
    description: 'The administrator password for the server'
    hidden: true
  availability_zone:
    type: string
    description: 'Name of availability zone in which to create the instance'
  storage_account:
    type: string
    description: 'The storage account'
  resource_group:
    type: string
    description: 'The Azure resource group'
  network-id__for__virtual-network:
    type: string
    description: 'Generated to reference ''virtual-network'' network.'
    default: 'virtual-network'
parameter_groups:
    - { label: 'Image Parameters', parameters: [admin_pass, admin_user, flavor, resource_group, storage_account] }
    - { label: 'Network Parameters', parameters: [availability_zone, network-id__for__virtual-network] }
resources:
## REFERENCE {"virtual-network":{"type": "OS::Neutron::Net", "properties": {"network_id": "virtual-network", "external":"false", "subnets": [{"state":"Succeeded","cidr":"10.0.0.0\/16","name":"default_subnet","id":"default_subnet"}] }}}

  Ubuntu_Server_16_04-LTS:
    type: OS::Nova::Server
    properties:
      networks:
          - port: { get_resource: Ubuntu_Server_16_04-LTS__to__virtual-network__port  }
      name: "Ubuntu-Server-16-04-LTS"
      image: "Canonical:UbuntuServer:16.04-LTS:16.04.201709190" # UbuntuServer
      flavor: { get_param: flavor }
      admin_user: { get_param: admin_user }
      admin_pass: { get_param: admin_pass }
      availability_zone: { get_param: availability_zone }
      metadata: 
        "__os_type__" : "Linux"
    metadata:
      azure_properties:
        use_cloudinit: False
        storage_account: { get_param: storage_account }
        use_managed_disk: True
        volume_type: "hdd"
        resource_group: { get_param: resource_group }

  security-group1:
    type: OS::Neutron::SecurityGroup
    properties:
      name: security-group1
    metadata:
      azure_properties:
        resource_group: { get_param: resource_group }
        rules:
          - name: port-22
            description: 'open port 22'
            direction: Inbound
            protocol: '*'
            source_address_prefix: '*'
            destination_address_prefix: '*'
            destination_port_range: '*'
            source_port_range: '22'
            access: Allow
            priority: 101
          - name: rule2
            direction: Outbound
            protocol: 'Tcp'
            source_address_prefix: 'Internet'
            destination_address_prefix: '*'
            destination_port_range: '*'
            source_port_range: '*'
            access: Deny
            priority: 102

  Ubuntu_Server_16_04-LTS__to__virtual-network__port:
    type: OS::Neutron::Port
    properties:
      security_groups:
          - { get_resource: security-group1 }
      network_id: { get_param: network-id__for__virtual-network }
      replacement_policy: AUTO
      name: nic
    metadata:
      azure_properties:
        resource_group: { get_param: resource_group }

  security-group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: security-group
    metadata:
      azure_properties:
        resource_group: { get_param: resource_group }
        rules:
          - name: port-22
            description: 'open port 22'
            direction: Inbound
            protocol: '*'
            source_address_prefix: '*'
            destination_address_prefix: '*'
            destination_port_range: '*'
            source_port_range: '22'
            access: Allow
            priority: 101
          - name: rule2
            direction: Outbound
            protocol: 'Tcp'
            source_address_prefix: 'Internet'
            destination_address_prefix: '*'
            destination_port_range: '*'
            source_port_range: '*'
            access: Deny
            priority: 102

outputs:
  blueprint_url:
    description: Blueprint Origin URL
    value:  http://localhost:8080/landscaper/view/projects?open=ucdpadmin_00000000_0000_0000_0000_000000000002-OrionContent/default/xz-azure-test/security-group.yaml.yml

